title   Arch Linux DGX Spark
linux   /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-dgx-spark
initrd  /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-dgx-spark.img
architecture aa64
options archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% console=ttyS0,921600 console=tty0 earlycon=uart,mmio32,0x16A00000 nouveau.modeset=0 sbsa_gwdt.action=1 pci=pcie_bus_safe
