title   Arch Linux DGX Spark
linux   /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-dgx-spark
initrd  /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-dgx-spark.img
architecture aa64
options archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID%
