title   Arch Linux DGX Spark (serial console)
linux   /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-dgx-spark
initrd  /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-dgx-spark.img
architecture aa64
options archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% console=ttyAMA0,115200n8 console=tty0
