echo ""
echo "  Arch Linux for NVIDIA DGX Spark (GB10)"
echo ""
echo "  Install:"
echo "    archinstall --config /root/archinstall-config.json"
echo ""
echo "  This sets up linux-dgx-spark + Limine + snapper hooks automatically."
echo "  For manual install, see: https://wiki.archlinux.org/title/Installation_guide"
echo ""
